spring.datasource.url=jdbc:mysql://localhost:3306/appointmentdb
spring.datasource.username=root
spring.datasource.password=Lenovo@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# CORS allowed origins (comma separated, default is *)
cors.allowed-origins=http://localhost:3000
# CORS is configured centrally in a config class
# API Gateway will handle routing, authentication, and authorization
